import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { createColumnHelper, flexRender, getCoreRowModel, getPaginationRowModel, getSortedRowModel, useReactTable } from "@tanstack/react-table";
import { Plus, Search, ArrowUpDown, FileText, Trash2, Pencil, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from "@/components/ui/table";
import { Dialog,DialogContent,DialogTitle,DialogDescription,DialogFooter } from "@/components/ui/dialog";
import { PageHeader,ConnectionGate,Loading,Empty,ErrorNotice,CommitNotice } from "@/components/page";
import { useResource } from "@/lib/use-resource";
import { apiRequest } from "@/lib/api";
import { postsSchema, commitSchema } from "@shared/api-schema";
import type { PostSummary, CommitReceipt } from "@shared/contracts";
import { useSession } from "@/features/auth/session";
import dayjs from "dayjs";
const helper=createColumnHelper<PostSummary>();
export function PostsPage():React.JSX.Element {
 const {session}=useSession(),{data,error,loading,reload}=useResource("/api/posts",postsSchema);
 const [query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[category,setCategory]=useState("all"),[selected,setSelected]=useState<PostSummary|null>(null),[busy,setBusy]=useState(false),[writeError,setWriteError]=useState<Error|null>(null),[receipt,setReceipt]=useState<CommitReceipt|null>(null);
 const rows=useMemo(()=>(data || []).filter(post=>(post.title+post.path+post.tags.join(" ")).toLowerCase().includes(query.toLowerCase()) && (filter==="all" || filter==="error" && post.error || filter==="draft" && !post.error && post.draft || filter==="published" && !post.error && !post.draft) && (category==="all" || (post.category || "")===category)),[data,query,filter,category]);
 const categories=[...new Set((data || []).map(post=>post.category || ""))].sort();
 const columns=useMemo(()=>[
  helper.accessor("title",{header:({column})=><button className="sort-button" onClick={()=>column.toggleSorting()}>文章<ArrowUpDown size={13}/></button>,cell:({row})=><div className="article-cell"><FileText size={18}/><div>{row.original.error?<strong>{row.original.title}</strong>:<Link to={"/posts/edit?path="+encodeURIComponent(row.original.path)}><strong>{row.original.title}</strong></Link>}<small>{row.original.path.replace("src/content/posts/","")}</small></div></div>}),
  helper.accessor("draft",{header:"状态",cell:({row})=><Badge variant="secondary" className={row.original.error?"badge-error":row.original.draft?"":"badge-live"}>{row.original.error?"需修复":row.original.draft?"草稿":"已发布"}</Badge>}),
  helper.accessor("category",{header:"分类",cell:info=>info.getValue() || "未分类"}),
  helper.accessor("published",{header:({column})=><button className="sort-button" onClick={()=>column.toggleSorting()}>发布日期<ArrowUpDown size={13}/></button>,cell:info=>info.getValue()?dayjs(info.getValue()).format("YYYY.MM.DD"):"—"}),
  helper.display({id:"actions",header:"操作",cell:({row})=><div className="row-actions">{!row.original.error && <Button variant="ghost" size="icon" asChild><Link aria-label={"编辑 "+row.original.title} to={"/posts/edit?path="+encodeURIComponent(row.original.path)}><Pencil size={16}/></Link></Button>}<Button variant="ghost" size="icon" disabled={busy} aria-label={"删除 "+row.original.title} onClick={()=>{setSelected(row.original);setWriteError(null);}}><Trash2 size={16}/></Button></div>})
 ],[busy]);
 const table=useReactTable({data:rows,columns,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),initialState:{pagination:{pageSize:10}}});
 async function remove():Promise<void>{if(!selected)return;setBusy(true);setWriteError(null);try{setReceipt(await apiRequest("/api/post",commitSchema,{method:"DELETE",body:JSON.stringify({path:selected.path,expectedSha:selected.sha})}));setSelected(null);reload();}catch(reason){setWriteError(reason instanceof Error?reason:new Error("删除失败"));}finally{setBusy(false);}}
 return <><PageHeader eyebrow="CONTENT LIBRARY" title="文章管理" description="管理每一篇记录，让灵感从草稿走向发布。" action={<Button disabled={!session} asChild={Boolean(session)}>{session?<Link to="/posts/new"><Plus/>新建文章</Link>:<><Plus/>新建文章</>}</Button>}/>{receipt && <CommitNotice {...receipt}/>}<ConnectionGate><section className="panel"><div className="article-toolbar"><div className="search-field"><Search size={17}/><Input aria-label="搜索标题、路径或标签" placeholder="搜索文章、路径或标签…" value={query} onChange={event=>setQuery(event.target.value)}/></div><select aria-label="按状态筛选" value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">全部状态</option><option value="published">已发布</option><option value="draft">草稿</option><option value="error">格式异常</option></select><select aria-label="按分类筛选" value={category} onChange={event=>setCategory(event.target.value)}><option value="all">全部分类</option>{categories.map(name=><option value={name} key={name}>{name || "未分类"}</option>)}</select><Button variant="outline" size="icon" aria-label="刷新文章" disabled={loading} onClick={reload}><RefreshCw size={16}/></Button></div><ErrorNotice error={error} retry={reload}/>{loading?<Loading/>:rows.length?<><Table><TableHeader>{table.getHeaderGroups().map(group=><TableRow key={group.id}>{group.headers.map(header=><TableHead key={header.id}>{flexRender(header.column.columnDef.header,header.getContext())}</TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.map(row=><TableRow key={row.original.path}>{row.getVisibleCells().map(cell=><TableCell key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</TableCell>)}</TableRow>)}</TableBody></Table><div className="pagination"><small>共 {rows.length} 篇 · 第 {table.getState().pagination.pageIndex+1} / {table.getPageCount()} 页</small><div><Button variant="outline" size="sm" disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}>上一页</Button><Button variant="outline" size="sm" disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}>下一页</Button></div></div></>:!error && <Empty title={data?.length?"没有找到文章":"文章库，等你来填满"} description={data?.length?"试试其他搜索词或筛选条件。":"新建一篇文章，保存草稿或发布到博客。"} action={!data?.length?<Button asChild><Link to="/posts/new"><Plus/>写第一篇文章</Link></Button>:undefined}/>}</section><p className="info-note">“已发布”表示文章已提交且 draft 为 false。实际上线状态请查看发布记录。格式异常的文章只能在仓库修复，避免后台覆盖原内容。</p></ConnectionGate><Dialog open={Boolean(selected)} onOpenChange={open=>{if(!busy && !open)setSelected(null);}}><DialogContent><DialogTitle>删除这篇文章？</DialogTitle><DialogDescription>将从仓库删除「{selected?.title}」，并触发博客重新构建。已发布文章会在构建完成后下线。</DialogDescription><ErrorNotice error={writeError}/><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setSelected(null)}>取消</Button><Button variant="destructive" disabled={busy} onClick={()=>void remove()}>{busy?"删除中…":"确认删除"}</Button></DialogFooter></DialogContent></Dialog></>;
}

