import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import type { PostFields } from "@shared/contracts";
const textFields:Array<{key:"category"|"lang"|"author"|"sourceLink"|"licenseName"|"licenseUrl"|"password"|"passwordHint";label:string;placeholder?:string;type?:string}>=[
 {key:"category",label:"分类",placeholder:"未分类"},{key:"lang",label:"语言",placeholder:"留空使用博客默认语言"},
 {key:"author",label:"作者",placeholder:"留空使用博客默认作者"},{key:"sourceLink",label:"来源链接",placeholder:"https://"},
 {key:"licenseName",label:"许可证名称"},{key:"licenseUrl",label:"许可证链接",placeholder:"https://"},
 {key:"password",label:"文章密码",type:"password",placeholder:"留空则不加密"},{key:"passwordHint",label:"密码提示"}
];
export function EditorFields({fields,onChange,onCover}:{fields:PostFields;onChange:(fields:PostFields)=>void;onCover:()=>void}):React.JSX.Element {
 return <aside className="editor-options"><section className="panel options-section"><h2>文章信息</h2><label className="field-label">发布日期<Input type="date" value={fields.published.slice(0,10)} onChange={event=>onChange({...fields,published:event.target.value})}/></label><label className="field-label">更新日期<Input type="date" value={fields.updated?.slice(0,10) || ""} onChange={event=>onChange({...fields,updated:event.target.value || undefined})}/><small>已有文章保存时自动设为当天（上海时间）。</small></label><label className="field-label">描述<textarea rows={3} value={fields.description} onChange={event=>onChange({...fields,description:event.target.value})} placeholder="一句话介绍这篇文章…"/></label><label className="field-label">标签<Input value={fields.tags.join(", ")} onChange={event=>onChange({...fields,tags:event.target.value.split(/[,，]/).map(value=>value.trim())})} onBlur={()=>onChange({...fields,tags:[...new Set(fields.tags.filter(Boolean))]})} placeholder="用逗号分隔标签"/></label><label className="field-label">封面图片<Input value={fields.image} onChange={event=>onChange({...fields,image:event.target.value})} placeholder="相对路径、public 路径或远程 URL"/></label><Button type="button" variant="outline" size="sm" onClick={onCover}>从图片库选择封面</Button></section><details className="panel options-section" open><summary>更多文章设置</summary>{textFields.map(({key,label,placeholder,type})=><label className="field-label" key={key}>{label}<Input type={type || "text"} value={fields[key] || ""} onChange={event=>onChange({...fields,[key]:event.target.value})} placeholder={placeholder}/></label>)}{[{key:"draft",label:"草稿（不会公开展示）"},{key:"pinned",label:"置顶文章"},{key:"comment",label:"开启评论"},{key:"wikiExclude",label:"排除公开知识入口"}].map(({key,label})=><label className="check-field" key={key}><input type="checkbox" checked={Reflect.get(fields,key)===true} onChange={event=>onChange({...fields,[key]:event.target.checked})}/>{label}</label>)}<p className="field-help">文章密码仅用于博客现有的客户端加密。密码和草稿仍存在公开仓库中；请勿存放敏感信息。</p></details></aside>;
}

