import { Link } from "react-router-dom";
import { Feather, Plus, FileText, Tags, Image, ArrowUpRight, NotebookPen, CircleCheck, Clock3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useResource } from "@/lib/use-resource";
import { postsSchema } from "@shared/api-schema";
import { useSession } from "@/features/auth/session";
import { ConnectionGate, PageHeader, ErrorNotice, Loading, Empty } from "@/components/page";
import dayjs from "dayjs";
export function DashboardPage():React.JSX.Element {
 const {session,setup}=useSession(),{data:posts,error,loading,reload}=useResource("/api/posts",postsSchema);
 const valid=posts?.filter(post=>!post.error);
 const stats=[{label:"全部文章",value:posts?.length,icon:FileText,note:"包含已发布与草稿"},{label:"已发布",value:valid?.filter(post=>!post.draft).length,icon:CircleCheck,note:"已提交的公开文章"},{label:"草稿箱",value:valid?.filter(post=>post.draft).length,icon:NotebookPen,note:"留给下一次的灵感"},{label:"标签",value:valid?new Set(valid.flatMap(post=>post.tags)).size:undefined,icon:Tags,note:"串联知识与想法"}];
 return <><PageHeader eyebrow="YOUR WRITING SPACE" title="工作台" description={dayjs().format("YYYY 年 MM 月 DD 日")+" · 欢迎回到你的博客"} action={<Button asChild={Boolean(session)} disabled={!session}>{session?<Link to="/posts/new"><Plus/>写文章</Link>:<><Plus/>写文章</>}</Button>}/><section className="welcome-card"><div><span className="tiny-label"><span className="status-dot"/>BINGQILIN456'S BLOG</span><h2>每一个想法，<br/><span>都值得被记录。</span></h2><p>从一篇文章开始，把今天的学习与生活，<br className="desktop-break"/>留给未来的自己。</p><Button asChild variant="outline"><Link to={session?"/posts/new":"/settings"}>{session?"开始写作":"连接我的博客"}<ArrowUpRight/></Link></Button></div><div className="welcome-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-page"><Feather size={52}/><i/><i/><i/></div><span className="art-dot dot-one"/><span className="art-dot dot-two"/></div></section><div className="stat-grid">{stats.map(({label,value,icon:Icon,note})=><section className="stat-card" key={label}><div><span>{label}</span><Icon size={19}/></div><strong>{value===undefined?"—":value}</strong><small>{note}</small></section>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>最近的文章</h2><p>继续上次的记录</p></div><Link className="text-link" to="/posts">全部文章<ArrowUpRight size={15}/></Link></div><ConnectionGate><ErrorNotice error={error} retry={reload}/>{loading?<Loading/>:posts?.length?<div className="recent-list">{posts.slice(0,5).map(post=><Link key={post.path} to={post.error?"/posts":"/posts/edit?path="+encodeURIComponent(post.path)} className="recent-row"><span className="file-icon"><FileText size={20}/></span><div><strong>{post.title}</strong><small>{post.published?dayjs(post.published).format("YYYY.MM.DD"):"格式异常"} · {post.category || "未分类"}</small></div><Badge variant="secondary">{post.error?"需修复":post.draft?"草稿":"已发布"}</Badge><ArrowUpRight size={16}/></Link>)}</div>:!error && <Empty title="你的第一篇文章，从这里开始" description="写下一个想法，或上传已有文章到博客仓库。" action={<Button asChild><Link to="/posts/new"><Plus/>新建文章</Link></Button>}/>}</ConnectionGate></section><aside className="quick-panel"><div className="panel-heading"><div><h2>快捷入口</h2><p>照顾好你的内容</p></div></div>{[{path:"/posts",title:"整理文章",text:"修改、发布与管理草稿",icon:FileText},{path:"/taxonomy",title:"标签与分类",text:"让每篇记录各归其位",icon:Tags},{path:"/media",title:"图片素材",text:"上传配图，插入文章",icon:Image}].map(({path,title,text,icon:Icon})=><Link className="quick-link" to={path} key={path}><Icon size={20}/><div><strong>{title}</strong><small>{text}</small></div><ArrowUpRight size={15}/></Link>)}<div className="connection-summary"><Clock3 size={18}/><strong>{session?"内容由 GitHub 保存":"等待首次连接"}</strong><p>{setup?.repository || "仓库、OAuth 和部署配置完成后即可开始。"}</p><Link to="/settings" className="text-link">查看连接设置 ↗</Link></div></aside></div></>;
}

